# A generic, single database configuration.

[alembic]
# cesta ke skript??m migrac??
script_location = %(here)s/alembic

# p??id??n?? ko??enov?? slo??ky backendu na sys.path
prepend_sys_path = .
path_separator = os

# >>> D??LE??IT??: URL na Postgres (dev) <<<
# Alembic ji pou??ije p??i generov??n??/spou??t??n?? migrac??
sqlalchemy.url = postgresql+psycopg2://arte:arte@127.0.0.1:5432/arte_moderno


[post_write_hooks]
# (voliteln??; nech??v??me pr??zdn??)

# Logging
[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARNING
handlers = console
qualname =

[logger_sqlalchemy]
level = WARNING
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S

